global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9000
          - 192.168.100.121:9033