global: # especifica parâmetros que são válidos em todos os outros contextos de configuração.
  scrape_interval: 5s # intervalo de tempo em que será feito o pull
  scrape_timeout: 5s # tempo limite da requisição ao endpoint http de métricas

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9000
          - 192.168.100.121:8080